### ISSUE TITLE
Installation issue on Ubuntu 16.04

### ISSUE THREAD

**Issue by abhinavagrawal1995** [prodicus/vocabulary#38]
Faced the following error while installing via pip:

> Collecting vocabulary
> Using cached Vocabulary-1.0.2.tar.gz
> Complete output from command python setup.py egg_info:
> Traceback (most recent call last):
> File "", line 1, in 
> File "/tmp/pip-build-PWXQ1D/vocabulary/setup.py", line 19, in 
> with open(path.join(here, 'requirements.txt')) as f:
> IOError: [Errno 2] No such file or directory: '/tmp/pip-build-PWXQ1D/vocabulary/requirements.txt'
> 
> ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-PWXQ1D/vocabulary/

I ran `pip install requests` before this since it failed with the error "No such module : requests" earlier.

**Comment by lethargilistic** [comment]
Also breaks on Ubuntu 17.04, Python 3.

When this happens with my PyPI project, it's usually because I forgot to push the wheel to PyPI. Indeed, according to PyPI, the current version of vocabulary doesn't have a wheel.

**Comment by lethargilistic** [comment]
Seems to be the same issue as #34.

**Comment by prodicus** [comment]
@lethargilistic @abhinavagrawal1995 
Can confirm, tried it with both python3 and python2

Same traceback

```
# python3
$ pip install vocabulary --no-cache
Collecting vocabulary
  Downloading Vocabulary-1.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/sw/nsjcqtxs1yldt7y1gsqkfnw00000gn/T/pip-build-s5risjrz/vocabulary/setup.py", line 12, in <module>
        from vocabulary.version import VERSION
      File "/private/var/folders/sw/nsjcqtxs1yldt7y1gsqkfnw00000gn/T/pip-build-s5risjrz/vocabulary/vocabulary/__init__.py", line 5, in <module>
        from .vocabulary import Vocabulary
      File "/private/var/folders/sw/nsjcqtxs1yldt7y1gsqkfnw00000gn/T/pip-build-s5risjrz/vocabulary/vocabulary/vocabulary.py", line 25, in <module>
        import requests
    ModuleNotFoundError: No module named 'requests'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/sw/nsjcqtxs1yldt7y1gsqkfnw00000gn/T/pip-build-s5risjrz/vocabulary/

# python2
$ pip install vocabulary --no-cache
Collecting vocabulary
  Downloading Vocabulary-1.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/sw/nsjcqtxs1yldt7y1gsqkfnw00000gn/T/pip-build-z5VX_i/vocabulary/setup.py", line 12, in <module>
        from vocabulary.version import VERSION
      File "vocabulary/__init__.py", line 5, in <module>
        from .vocabulary import Vocabulary
      File "vocabulary/vocabulary.py", line 25, in <module>
        import requests
    ImportError: No module named requests

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/sw/nsjcqtxs1yldt7y1gsqkfnw00000gn/T/pip-build-z5VX_i/vocabulary/

```

Looking into it

**Comment by abhinavagrawal1995** [comment]
This error was fixed by running `pip install requests`
The stack trace pasted above is for a different error that I got AFTER
fixing this.


On May 14, 2017 1:30 PM, "Tasdik Rahman" <notifications@github.com> wrote:

@lethargilistic <https://github.com/lethargilistic> @abhinavagrawal1995
<https://github.com/abhinavagrawal1995>
Can confirm, tried it with both python3 and python2

Same traceback

# python3
$ pip install vocabulary --no-cache
Collecting vocabulary
  Downloading Vocabulary-1.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/sw/nsjcqtxs1yldt7y1gsqkfnw00000gn/T/pip-build-s5risjrz/vocabulary/setup.py",
line 12, in <module>
        from vocabulary.version import VERSION
      File "/private/var/folders/sw/nsjcqtxs1yldt7y1gsqkfnw00000gn/T/pip-build-s5risjrz/vocabulary/vocabulary/__init__.py",
line 5, in <module>
        from .vocabulary import Vocabulary
      File "/private/var/folders/sw/nsjcqtxs1yldt7y1gsqkfnw00000gn/T/pip-build-s5risjrz/vocabulary/vocabulary/vocabulary.py",
line 25, in <module>
        import requests
    ModuleNotFoundError: No module named 'requests'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in
/private/var/folders/sw/nsjcqtxs1yldt7y1gsqkfnw00000gn/T/pip-build-s5risjrz/vocabulary/

# python2
$ pip install vocabulary --no-cache
Collecting vocabulary
  Downloading Vocabulary-1.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/sw/nsjcqtxs1yldt7y1gsqkfnw00000gn/T/pip-build-z5VX_i/vocabulary/setup.py",
line 12, in <module>
        from vocabulary.version import VERSION
      File "vocabulary/__init__.py", line 5, in <module>
        from .vocabulary import Vocabulary
      File "vocabulary/vocabulary.py", line 25, in <module>
        import requests
    ImportError: No module named requests

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in
/private/var/folders/sw/nsjcqtxs1yldt7y1gsqkfnw00000gn/T/pip-build-z5VX_i/vocabulary/


Looking into it

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/prodicus/vocabulary/issues/38#issuecomment-301297183>,
or mute the thread

**Comment by prodicus** [comment]
@abhinavagrawal1995 
The dependencies should get installed for the new user if they are not installed already. Doing a `pip install <dependency-name>` would not be a good way to forward if we have multiple dependencies listed.
